# Exercise: solutions/01_pods/pods04.yaml
# Topic: Resource Requests, Limits & Quality of Service (QoS) Classes
# Reference Guide: https://dnf0.github.io/kubelings/guides/01-pods/
#
# Reference Solution

apiVersion: v1
kind: Pod
metadata:
  name: qos-guaranteed-pod
spec:
  containers:
  - name: backend
    image: redis:alpine
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 256Mi
