# Chapter 18: Advanced Admission Webhooks & Dynamic Interception
# Exercise 18.1: MutatingWebhookConfiguration Manifest (Solution)

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-defaults-mutator
webhooks:
  - name: mutate-pods.kubelings.io
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: webhook-system
        name: mutator-svc
        path: /mutate
        port: 443
      caBundle: "QWxhZGRpbjpvcGVuIHNlc2FtZQ=="
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
    failurePolicy: Fail
