# Chapter 20: Declarative Customization with Kustomize
# Exercise 20.3: Kustomize Strategic Merge & JSON6902 Target Patches (Solution)

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: webapp
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
      - op: add
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
