# Exercise: solutions/03_config_secrets/config03.yaml
# Topic: Secrets: Base64 Encoding & stringData
# Reference Guide: https://dnf0.github.io/kubelings/guides/03-config-secrets/
#
# Reference Solution

apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: YWRtaW4=
  password: c3VwZXJzZWNyZXQ=
stringData:
  api_key: "prod-api-key-998877"
