# Exercise: solutions/03_config_secrets/config05.yaml
# Topic: Immutable ConfigMaps and Secrets
# Reference Guide: https://dnf0.github.io/kubelings/guides/03-config-secrets/
#
# Reference Solution

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-feature-flags
immutable: true
data:
  NEW_UI: "true"
  MAX_WORKERS: "8"
